variables:
  GOOGLE_CREDENTIALS: $GCP_SERVICE_ACCOUNT_KEY
  GOOGLE_PROJECT: $GCP_PROJECT_ID
  GOOGLE_REGION: $GCP_REGION
  DOCKER_IMAGE_NAME: "iaiperi04772/app"

stages:
  - terraform
  - build
  - push

before_script:
  - cd infrastructure
  - echo "$GOOGLE_CREDENTIALS" > /tmp/account.json
  - terraform init -backend-config="credentials=/tmp/account.json" -input=false

terraform_plan:
  stage: terraform
  script:
    - terraform plan -out=tfplan
    - ls -la # Проверьте наличие файла tfplan
  artifacts:
    paths:
      - tfplan
  only:
    - merge_requests
    - main
  tags:
    - test

terraform_apply:
  stage: terraform
  script:
    - ls -la # Проверяем наличие файла tfplan
    - terraform apply -auto-approve tfplan
  only:
    - main
  tags:
    - test
  dependencies:
    - terraform_plan




# ----- DOCKER -----

# build:
#   stage: build
#   script:
#     - docker build -t $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA .
#   only:
#     - main  

# push:
#   stage: push
#   script:
#     # Логин в Docker Hub
#     - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
#     # Тегирование и пуш образа
#     - docker tag $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA $DOCKER_IMAGE_NAME:latest
#     - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA
#     - docker push $DOCKER_IMAGE_NAME:latest
#   only:
#     - main  
