apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-lb
  namespace: frontend
spec:
  podSelector:
    matchLabels: {}  
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0  
        except:
        - 10.0.0.0/8 
    ports:
    - protocol: UDP
      port: 53  
