apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-backend
spec:
  podSelector: {}  
  egress:
  - to:
    - podSelector:
        matchLabels: {}  
      namespaceSelector:
        matchLabels:
          tier: backend
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53  
