apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-frontend
spec:
  podSelector: {}  
  egress:
    - from:
      - podSelector:
          matchLabels: {}
      namespaceSelector:
        matchLabels:
          tier: frontend
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
      ports:
      - protocol: UDP
        port: 53
