apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    tier: frontend

---

apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    tier: beckend

---

apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    tier: database